# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created: Sat May 09 22:27:01 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 639)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.buttonMoveUp = QtGui.QPushButton(self.centralwidget)
        self.buttonMoveUp.setObjectName("buttonMoveUp")
        self.verticalLayout_3.addWidget(self.buttonMoveUp)
        self.buttonMoveDown = QtGui.QPushButton(self.centralwidget)
        self.buttonMoveDown.setObjectName("buttonMoveDown")
        self.verticalLayout_3.addWidget(self.buttonMoveDown)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 3, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.buttonRemoveSelected = QtGui.QPushButton(self.centralwidget)
        self.buttonRemoveSelected.setObjectName("buttonRemoveSelected")
        self.horizontalLayout_4.addWidget(self.buttonRemoveSelected)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 2, 1, 1)
        self.listWidgetAvailable = QtGui.QListWidget(self.centralwidget)
        self.listWidgetAvailable.setMinimumSize(QtCore.QSize(250, 400))
        self.listWidgetAvailable.setObjectName("listWidgetAvailable")
        self.gridLayout.addWidget(self.listWidgetAvailable, 2, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonAdd = QtGui.QPushButton(self.centralwidget)
        self.buttonAdd.setObjectName("buttonAdd")
        self.verticalLayout_4.addWidget(self.buttonAdd)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 1, 1, 1)
        self.labelSelectedLayouts = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelSelectedLayouts.setFont(font)
        self.labelSelectedLayouts.setObjectName("labelSelectedLayouts")
        self.gridLayout.addWidget(self.labelSelectedLayouts, 1, 2, 1, 1)
        self.labelAvailableLayouts = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelAvailableLayouts.setFont(font)
        self.labelAvailableLayouts.setObjectName("labelAvailableLayouts")
        self.gridLayout.addWidget(self.labelAvailableLayouts, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonSaveHtmlFile = QtGui.QPushButton(self.centralwidget)
        self.buttonSaveHtmlFile.setObjectName("buttonSaveHtmlFile")
        self.horizontalLayout_5.addWidget(self.buttonSaveHtmlFile)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 2, 1, 1)
        self.listWidgetSelected = QtGui.QListWidget(self.centralwidget)
        self.listWidgetSelected.setMinimumSize(QtCore.QSize(250, 400))
        self.listWidgetSelected.setObjectName("listWidgetSelected")
        self.gridLayout.addWidget(self.listWidgetSelected, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuLoadLayoutTemplate = QtGui.QAction(MainWindow)
        self.menuLoadLayoutTemplate.setObjectName("menuLoadLayoutTemplate")
        self.menuSaveLayoutTemplate = QtGui.QAction(MainWindow)
        self.menuSaveLayoutTemplate.setObjectName("menuSaveLayoutTemplate")
        self.menuSaveHtmlFile = QtGui.QAction(MainWindow)
        self.menuSaveHtmlFile.setObjectName("menuSaveHtmlFile")
        self.menuFile.addAction(self.menuLoadLayoutTemplate)
        self.menuFile.addAction(self.menuSaveLayoutTemplate)
        self.menuFile.addAction(self.menuSaveHtmlFile)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Responsive Layout Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMoveUp.setText(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMoveDown.setText(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRemoveSelected.setText(QtGui.QApplication.translate("MainWindow", "Remove Selected Element", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAdd.setText(QtGui.QApplication.translate("MainWindow", "Add >>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelectedLayouts.setText(QtGui.QApplication.translate("MainWindow", "Selected Layout Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAvailableLayouts.setText(QtGui.QApplication.translate("MainWindow", "Available Layout Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveHtmlFile.setText(QtGui.QApplication.translate("MainWindow", "Save to HTML File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoadLayoutTemplate.setText(QtGui.QApplication.translate("MainWindow", "Load Layout Template", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSaveLayoutTemplate.setText(QtGui.QApplication.translate("MainWindow", "Save to Layout Template", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSaveHtmlFile.setText(QtGui.QApplication.translate("MainWindow", "Save to HTML File", None, QtGui.QApplication.UnicodeUTF8))

